### ISSUE TITLE
`initialize': No such file or directory @ rb_sysopen 

### ISSUE THREAD

**Issue by infominer33** [bhaak/github-feeds#1]
just cloned the repository to give it a whirl:

% `ruby github-feeds.rb --owner hyperledger --repository aries-rfcs`
```
Traceback (most recent call last):
	2: from github-feeds.rb:60:in `<main>'
	1: from github-feeds.rb:60:in `open'
github-feeds.rb:60:in `initialize': No such file or directory @ rb_sysopen - feeds/hyperledger_aries-rfcs_issues.rss (Errno::ENOENT)
```
% `ruby github-feeds.rb --pulls --owner hyperledger --repository aries-rfcs`
```
Traceback (most recent call last):
	2: from github-feeds.rb:60:in `<main>'
	1: from github-feeds.rb:60:in `open'
github-feeds.rb:60:in `initialize': No such file or directory @ rb_sysopen - feeds/hyperledger_aries-rfcs_pull_requests.rss (Errno::ENOENT)
```
% `ruby --version`
```
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
```

**Comment by bhaak** [comment]
The directory "feeds" doesn't exist. There is code that should ensure that the output directory exists but actually it creates a directory with the name of the owner.

Sorry for taking so long to respond. I didn't notice the open issue. Ironically that is exactly why I coded this little program but I forgot to add the feed of this repository to my RSS reader.

**Comment by infominer33** [comment]
doing a little coding myself now and probably could have fixed that myself. Maybe I'll try again, since I've not yet found an entirely satisfactory way to do this.

Something like this app would go great with a github action and [pluto feedreader](https://github.com/feedreader)!
